services:
  nova-bot:
    container_name: nova-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/Nova-bot

    restart: always
    command: ["python3", "telegram_bot.py"]
